import assert from 'node:assert/strict';
import {expm,matVec,analyze,eigenvalues,trajectory} from '../dist/math.js';
const close=(a,b,tol=1e-8)=>assert.ok(Math.abs(a-b)<=tol*Math.max(1,Math.abs(b)),`${a} ≠ ${b}`);
const vector=(a,b)=>a.forEach((v,i)=>close(v,b[i]));
const spectra=(A,expected)=>{const got=eigenvalues(A).sort((a,b)=>a.re-b.re||a.im-b.im);expected.sort((a,b)=>a[0]-b[0]||a[1]-b[1]);got.forEach((v,i)=>{close(v.re,expected[i][0]);close(v.im,expected[i][1]);});};
const rotation=[[0,-1],[1,0]];vector(matVec(expm(rotation,2*Math.PI),[2,0]),[2,0]);assert.equal(analyze(rotation).kind,'neutral');
const shear=[[0,1],[0,0]];vector(matVec(expm(shear,4),[0,1]),[4,1]);assert.equal(analyze(shear).kind,'unstable');
const jordan=[[-1,1],[0,-1]];vector(matVec(expm(jordan,2),[0,1]),[2*Math.exp(-2),Math.exp(-2)]);assert.equal(analyze(jordan).kind,'stable');
const nilpotent=[[0,1,0],[0,0,1],[0,0,0]];vector(matVec(expm(nilpotent,3),[0,0,1]),[4.5,3,1]);assert.equal(analyze(nilpotent).kind,'unstable');
assert.equal(analyze([[-1,0,0],[0,-2,0],[0,0,0]]).kind,'neutral');assert.equal(analyze([[0,1,0],[0,0,0],[0,0,-1]]).kind,'unstable');
assert.equal(analyze([[0,0],[0,0]]).kind,'neutral');assert.equal(analyze([[0,1],[1e-12,0]]).title,'Saddle');
assert.equal(analyze([[-1,0,0],[0,-1e-8,0],[0,0,0]]).kind,'neutral');
assert.equal(analyze([[-1,0,0],[0,1e-8,0],[0,0,-1e-8]]).title,'Saddle');
spectra([[0,0,6],[1,0,-11],[0,1,6]],[[1,0],[2,0],[3,0]]);
spectra([[0,0,-1],[1,0,0],[0,1,0]],[[-1,0],[.5,-Math.sqrt(3)/2],[.5,Math.sqrt(3)/2]]);
spectra([[-.25,-1.4,0],[1.4,-.25,0],[0,0,-.55]],[[-.55,0],[-.25,-1.4],[-.25,1.4]]);
spectra([[1e-6,0,0],[0,2e-6,0],[0,0,3e-6]],[[1e-6,0],[2e-6,0],[3e-6,0]]);
const orbit=trajectory(rotation,[3,0],30);close(Math.hypot(...orbit.at(-1).x),3);assert.equal(orbit.length,901);
const growth=trajectory([[20,0],[0,20]],[1,1],30);assert.ok(growth.length<901);assert.ok(growth.every(p=>p.x.every(Number.isFinite)));
console.log('Passed: analytic solutions, 2D/3D spectra, repeated eigenvalues, stability, long rotation, and bounded growth.');
