import assert from 'node:assert/strict';
import {HOPF_A, field, equilibriaFor, saddleDirections, rk4, integrate, phasePaths, equilibriumBranches} from '../../dist/apps/bifurcations-2d/js/math.js';

const close = (actual, expected, tolerance = 1e-10) => assert.ok(
  Math.abs(actual - expected) <= tolerance * Math.max(1, Math.abs(expected)), `${actual} ≠ ${expected}`
);
const closePoint = (actual, expected, tolerance) => actual.forEach((value, i) => close(value, expected[i], tolerance));
const norm = point => Math.hypot(...point);
const difference = (a, b) => a.map((value, i) => value - b[i]);

for (const [a, count] of [[-4, 4], [-1.000001, 4], [-1, 3], [-.999999, 2], [0, 2], [.999999, 2], [1, 1], [1.000001, 0], [2, 0]]) {
  const equilibria = equilibriaFor(a);
  assert.equal(equilibria.length, count, `Equilibrium count at a=${a}`);
  assert.equal(new Set(equilibria.map(e => e.id)).size, count);
  for (const equilibrium of equilibria) {
    const {x, y, determinant, trace} = equilibrium;
    assert.ok(norm(field(a, [x, y])) < 1e-12, `Equilibrium residual at a=${a}`);
    close(trace, 2 * x + 1);
    close(determinant, 2 * x * (1 - 2 * y));
    if (equilibrium.id === 'upper-right' || equilibrium.id === 'lower-left') assert.equal(equilibrium.type, 'saddle');
    if (equilibrium.id === 'lower-right') assert.ok(equilibrium.type.startsWith('unstable-'));
  }
}
for (const a of [-1, 1]) {
  const fold = equilibriaFor(a).find(e => e.x === 0);
  assert.equal(fold.type, 'saddle-node');
  assert.equal(fold.y, a);
  assert.deepEqual(fold.eigenvalues, [0, 1]);
}

const hopf = equilibriaFor(HOPF_A).find(e => e.id === 'upper-left');
closePoint([hopf.x, hopf.y], [-.5, Math.sqrt(5) / 2]);
assert.equal(hopf.type, 'hopf');
close(hopf.trace, 0);
for (const eigenvalue of hopf.eigenvalues) {
  close(eigenvalue.re, 0);
  close(Math.abs(eigenvalue.im), Math.sqrt(Math.sqrt(5) - 1));
}
assert.ok(equilibriaFor(HOPF_A - .001).find(e => e.id === 'upper-left').type.startsWith('stable-'));
assert.ok(equilibriaFor(HOPF_A + .001).find(e => e.id === 'upper-left').type.startsWith('unstable-'));

// Eigenvectors used for shooting must solve Jv=λv with the indicated time direction.
for (const a of [-3, -1.513437373806419, -.5, .7228957882244, .99]) {
  for (const equilibrium of equilibriaFor(a)) {
    const directions = saddleDirections(equilibrium);
    if (equilibrium.type !== 'saddle') { assert.deepEqual(directions, []); continue; }
    assert.deepEqual(directions.map(d => d.kind), ['stable', 'unstable']);
    for (const {value, vector, kind} of directions) {
      close(norm(vector), 1);
      const {x, y} = equilibrium, [vx, vy] = vector;
      closePoint([2 * x * vx - 2 * y * vy, -2 * x * vx + vy], vector.map(v => value * v));
      assert.equal(value < 0, kind === 'stable');
    }
  }
}

// The exact invariant heteroclinic line reduces to a scalar logistic equation,
// supplying an independent reference for forward and backward integration.
const m = 1.324717957244746, aHet = -m - 1 / (4 * m);
const saddles = equilibriaFor(aHet).filter(e => e.type === 'saddle').sort((a, b) => a.x - b.x);
const [left, right] = saddles.map(e => e.x), gap = right - left, x0 = .2;
const lineY = x => m * x - 1 / (2 * m);
const exactX = t => left + gap / (1 + ((right - x0) / (x0 - left)) * Math.exp(-(m * m - 1) * gap * t));
const initial = [x0, lineY(x0)];
for (const direction of [-1, 1]) {
  const result = integrate(aHet, initial, {duration: 2.5, direction, tolerance: 1e-11, spacing: .02, bound: 10});
  assert.equal(result.stopped, 'time');
  const x = exactX(direction * 2.5);
  closePoint(result.points.at(-1), [x, lineY(x)], 2e-9);
  for (const point of result.points) close(point[1], lineY(point[0]), 1e-9);
}
const h = .002;
closePoint(rk4(aHet, initial, h), [exactX(h), lineY(exactX(h))], 2e-12);

for (const [a, point] of [[-.4, [-.8, 1.1]], [.8, [-.4, 1.2]], [-2, [.2, -.8]]]) {
  const forward = integrate(a, point, {duration: .4, tolerance: 1e-11, spacing: .015, bound: 10});
  const backward = integrate(a, forward.points.at(-1), {duration: .4, direction: -1, tolerance: 1e-11, spacing: .015, bound: 10});
  assert.equal(forward.stopped, 'time');
  assert.equal(backward.stopped, 'time');
  closePoint(backward.points.at(-1), point, 2e-9);
}
const fixed = equilibriaFor(0)[0];
assert.equal(integrate(0, [fixed.x, fixed.y]).stopped, 'equilibrium');
const escaping = integrate(2, [3, 0], {duration: 30, bound: 6});
assert.equal(escaping.stopped, 'escape');
assert.ok(escaping.points.every(point => point.every(Number.isFinite)));

// All returned paths are ordered in forward time, including stable branches
// generated by backward shooting and the backward half of user trajectories.
for (const a of [-1.5, .75]) {
  const paths = phasePaths(a, [[-.7, .6]], {bound: 8, spacing: .025, duration: 3});
  const saddles = equilibriaFor(a).filter(e => e.type === 'saddle');
  assert.equal(paths.length, saddles.length * 4 + 1);
  for (const path of paths) {
    assert.ok(path.points.length >= 2);
    assert.ok(path.points.every(point => point.length === 2 && point.every(Number.isFinite)));
    if (path.kind === 'stable' || path.kind === 'unstable') {
      const anchor = path.kind === 'stable' ? path.points.at(-1) : path.points[0];
      assert.ok(saddles.some(e => norm(difference(anchor, [e.x, e.y])) < 1e-12));
    }
    for (let i = 1; i < path.points.length; i++) {
      const previous = path.points[i - 1], point = path.points[i];
      const delta = difference(point, previous), length = norm(delta);
      if (length < 1e-12) continue;
      const velocity = field(a, point.map((value, j) => (value + previous[j]) / 2));
      assert.ok(delta[0] * velocity[0] + delta[1] * velocity[1] >= -1e-13,
        `${path.kind} path has a segment opposing the vector field at a=${a}`);
    }
  }
}

// Sampling must terminate both sides of each branch exactly at its fold, with
// no gap or interpolation across the parameter region where it does not exist.
const branches = equilibriumBranches(-3, 1.2, 521);
for (const branch of branches) {
  let previousA = -Infinity;
  for (const [a, x] of branch.points) {
    assert.ok(a >= previousA && a >= -3 && a <= 1.2);
    previousA = a;
    const branchName = branch.id.split('-')[0];
    const equilibrium = equilibriaFor(a).find(e => e.id.startsWith(branchName) && Math.abs(e.x - x) < 1e-10);
    assert.ok(equilibrium, `No equilibrium corresponds to plotted branch ${branch.id} at ${a}`);
  }
}
for (const id of ['upper-left', 'upper-right', 'lower-left', 'lower-right']) {
  const samples = branches.filter(branch => branch.id === id).flatMap(branch => branch.points);
  const foldA = id.startsWith('upper') ? 1 : -1;
  assert.ok(samples.length > 2);
  closePoint(samples.at(-1), [foldA, 0], 0);
  assert.ok(samples.every(([a]) => a <= foldA));
}
assert.ok(branches.some(branch => branch.points.some(([a, x]) => a === HOPF_A && Math.abs(x + .5) < 1e-12)));

console.log('Passed: equilibria and folds, Hopf stability, saddle eigendirections, exact invariant-line integration, reversible integration, finite forward-oriented paths, and branch endpoints.');
