"""Package each application's named ES modules for direct file:// opening."""

import argparse
import json
from pathlib import Path
import re


APPS = Path(__file__).resolve().parents[1] / "dist" / "apps"
# The app uses only local named imports and exported const/function declarations.
IMPORT = re.compile(
    r"^import\s+\{([\w,\s]+)\}\s+from\s+(['\"])(\./[\w-]+\.js)\2;[ \t]*$",
    re.MULTILINE,
)
EXPORT = re.compile(r"^export (?:const\s+|function\*?\s+)(\w+)", re.MULTILINE)


def build_bundle(directory):
    chunks = ["// Generated by scripts/build_file_bundle.py. Edit the source modules instead.\n",
              "(() => {\n'use strict';\nconst modules = Object.create(null);\n"]
    visited, visiting = set(), set()

    def visit(name):
        if name in visited:
            return
        if name in visiting:
            raise ValueError(f"Circular module dependency: {name}")
        visiting.add(name)
        source = (directory / name).read_text(encoding="utf-8")

        def import_names(match):
            dependency = match[3][2:]
            visit(dependency)
            return f"const {{{match[1]}}} = modules[{json.dumps(dependency)}];"

        source = IMPORT.sub(import_names, source)
        exports = EXPORT.findall(source)
        source = EXPORT.sub(lambda match: match[0][len("export "):], source)
        if re.search(r"^(?:import|export)\b", source, re.MULTILINE):
            raise ValueError(f"Unsupported module syntax in {name}")
        chunks.append(f"\n// {name}\nmodules[{json.dumps(name)}] = (() => {{\n")
        chunks.append(source.rstrip() + "\n")
        chunks.append("return {" + ",".join(exports) + "};\n})();\n")
        visiting.remove(name)
        visited.add(name)

    visit("app.js")
    chunks.append("})();\n")
    return "".join(chunks)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if any saved bundle is stale")
    args = parser.parse_args()
    for entry in sorted(APPS.glob("*/js/app.js")):
        output = entry.with_name("app.bundle.js")
        bundle = build_bundle(entry.parent)
        if args.check:
            if not output.exists() or output.read_text(encoding="utf-8") != bundle:
                parser.exit(1, f"{output} is stale. Run python3 scripts/build_file_bundle.py\n")
            print(f"{entry.parent.parent.name}: bundle matches the source modules.")
        else:
            output.write_text(bundle, encoding="utf-8")
            print(f"Created {output}")
